LATEXMKRC=$(realpath latexmkrc)

LATEXMK_OPTIONS=-f $\
				-synctex=1 $\
				-interaction=nonstopmode $\
				-recorder $\
				-file-line-error $\
				-shell-escape $\
				-halt-on-error $\
				-r $(LATEXMKRC)

CHKTEX_OPTIONS=--localrc ./chktexrc $\
			   --headererr $\
			   --inputfiles $\
			   --format=1 $\
			   --verbosity=2

LATEXINDENT_OPTIONS=--local=indentconfig.yaml $\
					--overwrite


asy:
	@for asyfile in $(shell find . -name "*.asy"); do \
		DIR=`dirname $$asyfile`; \
		FILE=`basename $$asyfile`; \
		echo -e "\nCompiling $$asyfile\n"; \
		asy $$FILE -cd $$DIR; \
	done

# remove auxiliary files generated by latexmk AND the PDF file
clean:
	@for texfile in $(shell find . -name "*.tex"); do \
		DIR=`dirname $$texfile`; \
		latexmk -C $$texfile -outdir=$$DIR; \
	done

# remove auxiliary files generated by latexmk BUT not the PDF file
cleanaux:
	@for texfile in $(shell find . -name "*.tex"); do \
		DIR=`dirname $$texfile`; \
		latexmk -c $$texfile -outdir=$$DIR; \
	done

# remove backup files that generated by latexindent.pl
cleanbak:
	@$(shell find . -type f -regextype grep -regex ".*\.\(bak\d*\|log\)$$" -exec rm -f {} \;)


# lint all tex files
lint:
	@chktex $(CHKTEX_OPTIONS) $(shell find . -name "*.tex")

# format all tex, cls, sty files
# all files and directories should not contain any white space in their names
format:
	@for file in $(shell find . -regex ".*\.\(tex\|cls\|sty\)\$$"); do \
		echo "\nFormatting $$file ...\n"; \
		latexindent $(LATEXINDENT_OPTIONS) $$file; \
	done

format/%: %
	@for file in $(shell find $< -regex ".*\.\(tex\|cls\|sty\)$$"); do \
		echo "\nFormatting $$file ...\n"; \
		latexindent $(LATEXINDENT_OPTIONS) $$file; \
	done

updatecls: cleanaux
	@mkdir -p $(shell kpsewhich -var-value=TEXMFHOME)/tex/latex/local/class
	@find . -name "*.cls" -exec cp {} $(shell kpsewhich -var-value=TEXMFHOME)/tex/latex/local/class \; \

%.format: %.tex
	@latexindent $(LATEXINDENT_OPTIONS) $<

%.pdf: %.tex
	@latexmk $(LATEXMK_OPTIONS) -pdf -pvc -outdir=$(shell dirname $<) $(shell basename $<)

%.dvi: %.tex
	@latexmk $(LATEXMK_OPTIONS) -dvi -pvc -outdir=$(shell dirname $<) $(shell basename $<)

%.ps: %.tex
	@latexmk $(LATEXMK_OPTIONS) -ps -pvc -outdir=$(shell dirname $<) $(shell basename $<)

%.pdf.o: %.tex
	@latexmk $(LATEXMK_OPTIONS) -pdf -outdir=$(shell dirname $<) $(shell basename $<)

%.dvi.o: %.tex
	@latexmk $(LATEXMK_OPTIONS) -dvi -outdir=$(shell dirname $<) $(shell basename $<)

%.ps.o: %.tex
	@latexmk $(LATEXMK_OPTIONS) -ps -outdir=$(shell dirname $<) $(shell basename $<)

# lint specific TeX file
%.lint: %.tex
	@chktex $(CHKTEX_OPTIONS) $<

# format specific TeX file
%.format: %.tex
	@latexindent $(LATEXINDENT_OPTIONS) $<

linear-algebra:
	@$(MAKE) sheldon-axler-linear-algebra-done-right/main.pdf

.PHONY: kreyszig-functional-analysis
kreyszig-functional-analysis:
	@$(MAKE) kreyszig-functional-analysis/main.pdf

.PHONY: greub
greub:
	@$(MAKE) greub/main.pdf

.PHONY: james-dugundji-topology
james-dugundji-topology:
	@$(MAKE) james-dugundji-topology/main.pdf

.PHONY: vector-calculus
vector-calculus:
	@$(MAKE) vector-calculus/main.pdf

.PHONY: multivariable-mathematics
multivariable-mathematics:
	@$(MAKE) multivariable-mathematics/main.pdf

complex-analysis:
	@$(MAKE) ahlfors-complex-analysis/main.pdf

algebra:
	@$(MAKE) aluffi-algebra-chapter-0/main.pdf

lee-topological-manifolds:
	@$(MAKE) lee-topological-manifolds/main.pdf

lee-smooth-manifolds:
	@$(MAKE) lee-smooth-manifolds/main.pdf

tu-manifolds:
	@$(MAKE) tu-manifolds/main.pdf
